kind: pipeline
name: default

steps:
- name: frontend
  image: node
  commands:
  - cd app
  - npm install
  - node index.js
  - cd ..
  - echo "bah" > one-thing
  - ls -la

- name: backend
  image: node
  commands:
  - cat one-thing
